config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/index'

  get 'users/show'

  get 'users/destroy'

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  # resources :users

  resources :users do
    member do
      get :followers, :following
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :entries, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sample App", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="" class= "dropdown-toggle" data-toggle="dropdown">
                  Account <b class = "caret"></b>
                </a>
                <ul class = "dropdown-menu">
                  <li><%= link_to "Profile", current_user %> </li>
                  <li class= "divider"> </li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>

          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<%= yield %>
</div>

</body>
</html>